### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by jcapriot**
update requirements to match `zarr` requirements.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by joshmoore — APPROVED** [review]
Thanks for catching this, @jcapriot!

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/324 ) to patch the repodata of the old package.

**Comment by joshmoore** [comment]
Wow. TIL. Is this something I should be aware of, @jakirkham?

**Comment by jakirkham** [comment]
It's a good thing to be aware of. Mainly it is useful in cases like this one where a constraint needs fixing after a package is published. Patching the repodata allows old packages constraints to be updated. There is [some more info and some examples in this doc]( https://conda-forge.org/docs/user/faq.html#faq-abi-incompatibility ).

**Pull request merged**
